# Generated by Django 3.0.5 on 2020-06-09 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_productinbasket_session_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinbasket',
            old_name='number',
            new_name='nmb',
        ),
        migrations.RenameField(
            model_name='productinorder',
            old_name='number',
            new_name='nmb',
        ),
    ]
