# Generated by Django 3.0.5 on 2020-06-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200619_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='new_items',
            field=models.BooleanField(default=False),
        ),
    ]
