# Generated by Django 3.0.5 on 2020-06-19 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0002_auto_20200601_1805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'Subscriber', 'verbose_name_plural': 'Subscribers'},
        ),
    ]
