# Generated by Django 3.0.5 on 2020-06-20 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0003_auto_20200619_1314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'Подписчик', 'verbose_name_plural': 'Подписчики'},
        ),
    ]
